In [2]:
import numpy as np
import pandas as pd

In [3]:
trainData = pd.read_csv('C:\\Users\\ASMITPAUL\\Downloads\\train.csv')
trainData

OverallQual  GrLivArea  GarageCars  GarageArea  TotalBsmtSF  1stFlrSF  \
0               7       1820           1         240         1026      1133   
1               7       1646           1         240          918       918   
2               5       1316           2         484          926       926   
3              10       2402           3         672         3094      2402   
4               7       1253           2         402         1237      1253   
...           ...        ...         ...         ...          ...       ...   
1163            6       1400           2         440          672       672   
1164            7       1472           2         402          384       802   
1165            5        789           1         250          789       789   
1166            6       1661           1         377          992      1661   
1167            7       1442           2         500         1424      1442   

      FullBath  TotRmsAbvGrd  YearBuilt  YearRemodAdd  SalePrice  
0            2             8       1925          1950     184000  
1            2             7       1941          1950     164000  
2            1             6       1929          2001     130000  
3            2            10       2008          2008     555000  
4            2             6       1995          1996     176000  
...        ...           ...        ...           ...        ...  
1163         1             6       1978          1978     149500  
1164         2             7       1991          1992     160000  
1165         1             5       1948          1950     115000  
1166         1             8       1955          1996     165500  
1167         2             5       1990          1990     180500  

[1168 rows x 11 columns]

In [4]:
Y = np.matrix(trainData.iloc[:, 10:])

inputData = trainData.iloc[:, 0:10]
inputData.insert(loc = 0, column = 'Ones' ,value = 1)

X = inputData.to_numpy()
X = np.matrix(X)

print(X)
print(Y)

[[   1    7 1820 ...    8 1925 1950]
 [   1    7 1646 ...    7 1941 1950]
 [   1    5 1316 ...    6 1929 2001]
 ...
 [   1    5  789 ...    5 1948 1950]
 [   1    6 1661 ...    8 1955 1996]
 [   1    7 1442 ...    5 1990 1990]]
[[184000]
 [164000]
 [130000]
 ...
 [115000]
 [165500]
 [180500]]


In [5]:
parameters = np.linalg.inv(X.T @ X) @ X.T @ Y
print(list(np.array(parameters)))


[array([-1146530.37788969]), array([19689.26440613]), array([49.27276765]), array([11648.33265054]), array([16.01697717]), array([16.35853713]), array([15.92401482]), array([-6043.85572739]), array([451.16922121]), array([248.83798887]), array([294.50336048])]


In [6]:
testData = pd.read_csv('C:\\Users\\ASMITPAUL\\Downloads\\test.csv')
testData.insert(loc = 0, column = 'Ones', value = 1)
testData

Ones  OverallQual  GrLivArea  GarageCars  GarageArea  TotalBsmtSF  \
0       1            8       1970           3         753         1085   
1       1            6       1632           1         338         1240   
2       1            7       1223           2         480          600   
3       1            5       1559           2         812         1559   
4       1            4        630           1         286          630   
..    ...          ...        ...         ...         ...          ...   
287     1            6       1158           2         576         1158   
288     1            6        987           1         264          483   
289     1            6        848           2         420          848   
290     1            7       1266           2         388         1266   
291     1            6       1484           2         393          783   

     1stFlrSF  FullBath  TotRmsAbvGrd  YearBuilt  YearRemodAdd  SalePrice  
0        1120         2             8       2006          2006     281000  
1        1632         2             6       1958          1988     139000  
2         520         2             4       2005          2005     147400  
3        1559         1             5       1948          1973     153500  
4         630         1             3       1970          2002      86000  
..        ...       ...           ...        ...           ...        ...  
287      1158         1             5       2004          2004     158000  
288       483         1             5       1972          2007     118000  
289       848         1             4       2003          2003     140000  
290      1266         2             6       2007          2007     159895  
291       783         2             8       2005          2007     178900  

[292 rows x 12 columns]

In [7]:
prediction = []

for row in range(testData.shape[0]):
    predictedPrice = 0
    
    for column in range(testData.shape[1] - 1):
        predictedPrice = predictedPrice + testData.iloc[row,column]*parameters[column]
        
    prediction.append(predictedPrice)
    
prediction = np.asarray(prediction).squeeze(2)
prediction = prediction.squeeze(1)
prediction

array([272105.16989948, 178669.78124201, 179751.86300057, 177366.66110266,
        74951.93690219, 104159.26607936, 113773.00336077, 186092.39741749,
       212706.07012404, 159215.35215816, 217874.80995575, 117247.15565661,
       177040.65807324, 140199.29730141, 285605.07551407, 166569.80708851,
       205041.46670639, 231519.8045728 , 146644.92885948, 154953.63132379,
       236679.31604557, 267770.66799387, 197411.67995457, 125179.68066184,
       243204.43955124, 144682.58300732, 210988.91150088,  88184.0253935 ,
       137972.80170003, 169510.72116641, 280909.20116237, 180725.40512234,
       177472.56000447, 130067.09113324, 148909.7084672 , 142611.09222322,
         9647.73608394, 244751.87109098, 359232.49955507, 182369.72709883,
       133738.04687637, 102455.51572223,  63142.22801386,  60185.01499751,
       152996.32248561, 163045.4886073 ,  83014.67429301, 234325.45814599,
       103420.32026614, 164687.02056411, 124259.56951898, 231169.93575717,
       254960.23520098, 2

In [8]:
meanSale = np.mean(testData['SalePrice'])

ssTotal = np.sum((testData['SalePrice'] - meanSale)**2)
ssResidual = np.sum((testData['SalePrice'] - prediction)**2)

r2 = 1 - (ssResidual/ssTotal)
r2

0.8218751679815022